<body>
		<div id="head">
			<div class="flexslider">
  					<ul class="slides">
					    <li>
					      <img src="img/imagen1.jpg" />
					    </li>
					    <li>
					      <img src="img/imagen2.jpg" />
					    </li>
					    <li>
					      <img src="img/imagen3.jpg" />
					    </li>
					    <li>
					      <img src="img/imagen4.jpg" />
					    </li>
					    <li>
					      <img src="img/imagen5.jpg" />
					    </li>
					    <li>
					      <img src="img/imagen6.jpg" />
					    </li>
					 </ul>
				</div>
		</div>
		<div id="menu">
				<nav>
					<ul>
					<li> <a class="menu" href="inc/usuarios.php">Usuarios</a> </li>
					<li> <a class="menu" href="inc/eventos.php">Eventos</a> </li>
					<li> <a class="menu" href="inc/categoria.php">Categoria de Eventos</a> </li>
					<li> <a class="menu" href="inc/destinos.php">Destinos</a> </li>
					<li> <a class="menu" href="inc/clientes.php">Clientes</a> </li>
					<li> <a class="menu" href="inc/calendario.php">Calendario</a> </li>
					</ul>
					<div class="clear"> </div>
				</nav>
		</div>
		<div id ="titulo">
			<center>
				<h1>Sistema Central</h1>
				<h3 class="Subtitulo"><em>Ayudando en tu desarrollo Profesional</em></h3>
			</center>
		</div>
		<div id="seccion">